apiVersion: v1
kind: PersistentVolume
metadata:
  name: boomi-storage
spec:
  storageClassName: ""
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - vers=4
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: aksstorage20240226.file.core.windows.net
    path: /aksstorage20240226/aksnfs
--
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: boomi-storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi    
--
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mol
  labels:
    app: mol
spec:
  selector:
    matchLabels:
      app: mol
  replicas: 2
  template:
    metadata:
      labels:
        app: mol
    spec:
      terminationGracePeriodSeconds: 900
      volumes:
        - name: boomi-storage
          persistentVolumeClaim:
            claimName: pv-volume
      containers:
      - image: boomi/molecule:release
        name: molnode
        volumeMounts:
        - name: boomi-storage
          mountPath: /mnt/boomi
        ports:
        - containerPort: 9090
          protocol: TCP        
        resources:
          limits:
            cpu: "1000m"
            memory: "1024Mi"
          requests:
            cpu: "500m"
            memory: "768Mi"      
        readinessProbe:
          periodSeconds: 10
          initialDelaySeconds: 10
          httpGet:
            path: /_admin/readiness
            port: 9090
        livenessProbe:
          periodSeconds: 60
          httpGet:
            path: /_admin/liveness
            port: 9090
        env:
        - name: BOOMI_ATOMNAME
          value: "aks-mol"
        - name: ATOM_LOCALHOSTID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: INSTALL_TOKEN
          value: "molecule-fa18735a-4915-451d-8764-fc1636c86629"
        - name : BOOMI_ENVIRONMENTID
          value: "ae8230f6-bde3-4ab9-8676-ebbac87396a3"
