apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mol
  labels:
    app: mol
spec:
  selector:
    matchLabels:
      app: mol
  replicas: 2
  template:
    metadata:
      labels:
        app: mol
    spec:
      terminationGracePeriodSeconds: 900
      containers:
      - image: boomi/molecule:release
        name: molnode
        ports:
        - containerPort: 9090
          protocol: TCP        
        resources:
          limits:
            cpu: "1000m"
            memory: "1024Mi"
          requests:
            cpu: "500m"
            memory: "768Mi"      
        readinessProbe:
          periodSeconds: 10
          initialDelaySeconds: 10
          httpGet:
            path: /_admin/readiness
            port: 9090
        livenessProbe:
          periodSeconds: 60
          httpGet:
            path: /_admin/liveness
            port: 9090
        env:
        - name: BOOMI_ATOMNAME
          value: "aks-mol"
        - name: ATOM_LOCALHOSTID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: INSTALL_TOKEN
          value: "molecule-9946bc81-7410-4719-926c-6e42f6bf15f5"
        - name : BOOMI_ENVIRONMENTID
          value: "ae8230f6-bde3-4ab9-8676-ebbac87396a3"
